#!/bin/bash

reldir=`dirname $0`
cd $reldir
directory=`pwd`

echo "Directory is $directory"

find . -type f -name '*.php"
 ! -path "./vendor/*"
 ! -path "./other/*'
  -print0 |
while IFS= read -r -d '' file; do
    printf '%s\n' "$file"
done