#!/bin/bash

find . -type f -name "*.php" -print0 \
    -o -path "./Sources/minify" -prune \
    -o -path "./Sources/random_compat" -prune \
    -o -path "./Sources/ReCaptcha" -prune \
  | xargs -0 -n1 -P8 php -l \
  | (! grep -v "No syntax errors detected" )