#
# Your Crowdin credentials
#  - The _env versions replace the non-_env versions when using a public repository for security
#  - These environment variables must be defined in the env: section in your GitHub workflow
#
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path : "../."
base_url : "https://api.crowdin.com"

#
# Whether to use the existing file system hierarchy or to flatten it out
#  - true or false, SMF needs this to be true, since our hierarchy isn't flat (agreement.txt vs others)
#
preserve_hierarchy: true

#
# Source files & their translation patterns
#
files: [
 {
  source: "Languages/en_US/Admin.php",
  translation: "Languages/%locale_with_underscore%/Admin.php",
 },
 {
  source: "Languages/en_US/Agreement.php",
  translation: "Languages/%locale_with_underscore%/Agreement.php",
 },
 {
  source: "Languages/en_US/Alerts.php",
  translation: "Languages/%locale_with_underscore%/Alerts.php",
 },
 {
  source: "Languages/en_US/Drafts.php",
  translation: "Languages/%locale_with_underscore%/Drafts.php",
 },
 {
  source: "Languages/en_US/Editor.php",
  translation: "Languages/%locale_with_underscore%/Editor.php",
 },
 {
  source: "Languages/en_US/EmailTemplates.php",
  translation: "Languages/%locale_with_underscore%/EmailTemplates.php",
 },
 {
  source: "Languages/en_US/Errors.php",
  translation: "Languages/%locale_with_underscore%/Errors.php",
 },
 {
  source: "Languages/en_US/General.php",
  translation: "Languages/%locale_with_underscore%/General.php",
 },
 {
  source: "Languages/en_US/Help.php",
  translation: "Languages/%locale_with_underscore%/Help.php",
 },
 {
  source: "Languages/en_US/Install.php",
  translation: "Languages/%locale_with_underscore%/Install.php",
 },
 {
  source: "Languages/en_US/Login.php",
  translation: "Languages/%locale_with_underscore%/Login.php",
 },
 {
  source: "Languages/en_US/ManageBoards.php",
  translation: "Languages/%locale_with_underscore%/ManageBoards.php",
 },
 {
  source: "Languages/en_US/ManageCalendar.php",
  translation: "Languages/%locale_with_underscore%/ManageCalendar.php",
 },
 {
  source: "Languages/en_US/ManageMail.php",
  translation: "Languages/%locale_with_underscore%/ManageMail.php",
 },
 {
  source: "Languages/en_US/ManageMaintenance.php",
  translation: "Languages/%locale_with_underscore%/ManageMaintenance.php",
 },
 {
  source: "Languages/en_US/ManageMembers.php",
  translation: "Languages/%locale_with_underscore%/ManageMembers.php",
 },
 {
  source: "Languages/en_US/ManagePaid.php",
  translation: "Languages/%locale_with_underscore%/ManagePaid.php",
 },
 {
  source: "Languages/en_US/ManagePermissions.php",
  translation: "Languages/%locale_with_underscore%/ManagePermissions.php",
 },
 {
  source: "Languages/en_US/ManageScheduledTasks.php",
  translation: "Languages/%locale_with_underscore%/ManageScheduledTasks.php",
 },
 {
  source: "Languages/en_US/ManageSettings.php",
  translation: "Languages/%locale_with_underscore%/ManageSettings.php",
 },
 {
  source: "Languages/en_US/ManageSmileys.php",
  translation: "Languages/%locale_with_underscore%/ManageSmileys.php",
 },
 {
  source: "Languages/en_US/Manual.php",
  translation: "Languages/%locale_with_underscore%/Manual.php",
 },
 {
  source: "Languages/en_US/ModerationCenter.php",
  translation: "Languages/%locale_with_underscore%/ModerationCenter.php",
 },
 {
  source: "Languages/en_US/Modifications.php",
  translation: "Languages/%locale_with_underscore%/Modifications.php",
 },
 {
  source: "Languages/en_US/Modlog.php",
  translation: "Languages/%locale_with_underscore%/Modlog.php",
 },
 {
  source: "Languages/en_US/Packages.php",
  translation: "Languages/%locale_with_underscore%/Packages.php",
 },
 {
  source: "Languages/en_US/PersonalMessage.php",
  translation: "Languages/%locale_with_underscore%/PersonalMessage.php",
 },
 {
  source: "Languages/en_US/Post.php",
  translation: "Languages/%locale_with_underscore%/Post.php",
 },
 {
  source: "Languages/en_US/Profile.php",
  translation: "Languages/%locale_with_underscore%/Profile.php",
 },
 {
  source: "Languages/en_US/Reports.php",
  translation: "Languages/%locale_with_underscore%/Reports.php",
 },
 {
  source: "Languages/en_US/Search.php",
  translation: "Languages/%locale_with_underscore%/Search.php",
 },
 {
  source: "Languages/en_US/Stats.php",
  translation: "Languages/%locale_with_underscore%/Stats.php",
 },
 {
  source: "Languages/en_US/Themes.php",
  translation: "Languages/%locale_with_underscore%/Themes.php",
 },
 {
  source: "Languages/en_US/Timezones.php",
  translation: "Languages/%locale_with_underscore%/Timezones.php",
 },
 {
  source: "Languages/en_US/Who.php",
  translation: "Languages/%locale_with_underscore%/Who.php",
 },
 {
  source: "Languages/en_US/agreement.txt",
  translation: "Languages/%locale_with_underscore%/agreement.txt"
 }
]