<?php

header('Content-Type: text/javascript');

list($modified_since) = explode(';', $_SERVER['HTTP_IF_MODIFIED_SINCE']);
if (!empty($_SERVER['HTTP_IF_MODIFIED_SINCE']) && strtotime($modified_since) >= filemtime(__FILE__))
{
	header('HTTP/1.1 304 Not Modified');
	die;
}

// Are they a Charter Member?
if (isset($_GET['version']) && strpos($_GET['version'], 'SMF 1.1') !== false)
{
?>window.smfVersions = {
	'SMF': 'SMF 1.1 RC3',
	'SourcesAdmin.php': '1.1 RC3',
	'SourcesBoardIndex.php': '1.1 RC3',
	'SourcesCalendar.php': '1.1 RC3',
	'SourcesDisplay.php': '1.1 RC3',
	'SourcesDumpDatabase.php': '1.1 RC3',
	'SourcesErrors.php': '1.1 RC3',
	'SourcesHelp.php': '1.1 RC3',
	'SourcesKarma.php': '1.1 RC3',
	'SourcesLoad.php': '1.1 RC3',
	'SourcesLockTopic.php': '1.1 RC3',
	'SourcesLogInOut.php': '1.1 RC3',
	'SourcesManageAttachments.php': '1.1 RC3',
	'SourcesManageBans.php': '1.1 RC3',
	'SourcesManageBoards.php': '1.1 RC3',
	'SourcesManageCalendar.php': '1.1 RC3',
	'SourcesManageErrors.php': '1.1 RC3',
	'SourcesManageMembergroups.php': '1.1 RC3',
	'SourcesManageMembers.php': '1.1 RC3',
	'SourcesManageNews.php': '1.1 RC3',
	'SourcesManagePermissions.php': '1.1 RC3',
	'SourcesManagePosts.php': '1.1 RC3',
	'SourcesManageRegistration.php': '1.1 RC3',
	'SourcesManageSearch.php': '1.1 RC3',
	'SourcesManageServer.php': '1.1 RC3',
	'SourcesManageSmileys.php': '1.1 RC3',
	'SourcesMemberlist.php': '1.1 RC3',
	'SourcesMessageIndex.php': '1.1 RC3',
	'SourcesModSettings.php': '1.1 RC3',
	'SourcesModlog.php': '1.1 RC3',
	'SourcesMoveTopic.php': '1.1 RC3',
	'SourcesNews.php': '1.1 RC3',
	'SourcesNotify.php': '1.1 RC3',
	'SourcesPackageGet.php': '1.1 RC3',
	'SourcesPackages.php': '1.1 RC3',
	'SourcesPersonalMessage.php': '1.1 RC3',
	'SourcesPoll.php': '1.1 RC3',
	'SourcesPost.php': '1.1 RC3',
	'SourcesPrintpage.php': '1.1 RC3',
	'SourcesProfile.php': '1.1 RC3',
	'SourcesQueryString.php': '1.1 RC3',
	'SourcesRecent.php': '1.1 RC3',
	'SourcesRegister.php': '1.1 RC3',
	'SourcesReminder.php': '1.1 RC3',
	'SourcesRemoveTopic.php': '1.1 RC3',
	'SourcesRepairBoards.php': '1.1 RC3',
	'SourcesReports.php': '1.1 RC3',
	'SourcesSSI.php': '1.1 RC3',
	'SourcesSearch.php': '1.1 RC3',
	'SourcesSecurity.php': '1.1 RC3',
	'SourcesSendTopic.php': '1.1 RC3',
	'SourcesSplitTopics.php': '1.1 RC3',
	'SourcesStats.php': '1.1 RC3',
	'SourcesSubs.php': '1.1 RC3',
	'SourcesSubs-Auth.php': '1.1 RC3',
	'SourcesSubs-Boards.php': '1.1 RC3',
	'SourcesSubs-Charset.php' : '1.1 RC3',
	'SourcesSubs-Compat.php': '1.1 RC3',
	'SourcesSubs-Graphics.php': '1.1 RC3',
	'SourcesSubs-Members.php': '1.1 RC3',
	'SourcesSubs-Package.php': '1.1 RC3',
	'SourcesSubs-Post.php': '1.1 RC3',
	'SourcesSubs-Sound.php': '1.1 RC3',
	'SourcesThemes.php': '1.1 RC3',
	'SourcesViewQuery.php': '1.1 RC3',
	'SourcesWho.php': '1.1 RC3',
	'DefaultAdmin.template.php': '1.1 RC3',
	'DefaultBoardIndex.template.php': '1.1 RC3',
	'DefaultCalendar.template.php': '1.1 RC3',
	'DefaultCombat.template.php': '1.1 RC3',
	'DefaultDisplay.template.php': '1.1 RC3',
	'DefaultErrors.template.php': '1.1 RC3',
	'DefaultHelp.template.php': '1.1 RC3',
	'DefaultLogin.template.php': '1.1 RC3',
	'DefaultManageAttachments.template.php': '1.1 RC3',
	'DefaultManageBans.template.php': '1.1 RC3',
	'DefaultManageBoards.template.php': '1.1 RC3',
	'DefaultManageCalendar.template.php': '1.1 RC3',
	'DefaultManageMembergroups.template.php': '1.1 RC3',
	'DefaultManageMembers.template.php': '1.1 RC3',
	'DefaultManageNews.template.php': '1.1 RC3',
	'DefaultManagePermissions.template.php': '1.1 RC3',
	'DefaultManageSearch.template.php': '1.1 RC3',
	'DefaultManageSmileys.template.php': '1.1 RC3',
	'DefaultMemberlist.template.php': '1.1 RC3',
	'DefaultMessageIndex.template.php': '1.1 RC3',
	'DefaultModlog.template.php': '1.1 RC3',
	'DefaultMoveTopic.template.php': '1.1 RC3',
	'DefaultNotify.template.php': '1.1 RC3',
	'DefaultPackages.template.php': '1.1 RC3',
	'DefaultPersonalMessage.template.php': '1.1 RC3',
	'DefaultPoll.template.php': '1.1 RC3',
	'DefaultPost.template.php': '1.1 RC3',
	'DefaultPrintpage.template.php': '1.1 RC3',
	'DefaultProfile.template.php': '1.1 RC3',
	'DefaultRecent.template.php': '1.1 RC3',
	'DefaultRegister.template.php': '1.1 RC3',
	'DefaultReminder.template.php': '1.1 RC3',
	'DefaultReports.template.php': '1.1 RC3',
	'DefaultSearch.template.php': '1.1 RC3',
	'DefaultSendTopic.template.php': '1.1 RC3',
	'DefaultSettings.template.php': '1.1 RC3',
	'DefaultSplitTopics.template.php': '1.1 RC3',
	'DefaultStats.template.php': '1.1 RC3',
	'DefaultThemes.template.php': '1.1 RC3',
	'DefaultWho.template.php': '1.1 RC3',
	'DefaultWireless.template.php': '1.1 RC3',
	'DefaultXml.template.php': '1.1 RC3',
	'Defaultindex.template.php': '1.1 RC3',
	'TemplatesAdmin.template.php': '1.1 RC3',
	'TemplatesBoardIndex.template.php': '1.1 RC3',
	'TemplatesCalendar.template.php': '1.1 RC3',
	'TemplatesDisplay.template.php': '1.1 RC3',
	'TemplatesErrors.template.php': '1.1 RC3',
	'TemplatesHelp.template.php': '1.1 RC3',
	'TemplatesLogin.template.php': '1.1 RC3',
	'TemplatesManageAttachments.template.php': '1.1 RC3',
	'TemplatesManageBans.template.php': '1.1 RC3',
	'TemplatesManageBoards.template.php': '1.1 RC3',
	'TemplatesManageCalendar.template.php': '1.1 RC3',
	'TemplatesManageMembergroups.template.php': '1.1 RC3',
	'TemplatesManageMembers.template.php': '1.1 RC3',
	'TemplatesManageNews.template.php': '1.1 RC3',
	'TemplatesManagePermissions.template.php': '1.1 RC3',
	'TemplatesManageSearch.template.php': '1.1 RC3',
	'TemplatesManageSmileys.template.php': '1.1 RC3',
	'TemplatesMemberlist.template.php': '1.1 RC3',
	'TemplatesMessageIndex.template.php': '1.1 RC3',
	'TemplatesModlog.template.php': '1.1 RC3',
	'TemplatesMoveTopic.template.php': '1.1 RC3',
	'TemplatesNotify.template.php': '1.1 RC3',
	'TemplatesPackages.template.php': '1.1 RC3',
	'TemplatesPersonalMessage.template.php': '1.1 RC3',
	'TemplatesPoll.template.php': '1.1 RC3',
	'TemplatesPost.template.php': '1.1 RC3',
	'TemplatesPrintpage.template.php': '1.1 RC3',
	'TemplatesProfile.template.php': '1.1 RC3',
	'TemplatesRecent.template.php': '1.1 RC3',
	'TemplatesRegister.template.php': '1.1 RC3',
	'TemplatesReminder.template.php': '1.1 RC3',
	'TemplatesReports.template.php': '1.1 RC3',
	'TemplatesSearch.template.php': '1.1 RC3',
	'TemplatesSendTopic.template.php': '1.1 RC3',
	'TemplatesSettings.template.php': '1.1 RC3',
	'TemplatesSplitTopics.template.php': '1.1 RC3',
	'TemplatesStats.template.php': '1.1 RC3',
	'TemplatesThemes.template.php': '1.1 RC3',
	'TemplatesWho.template.php': '1.1 RC3',
	'TemplatesWireless.template.php': '1.1 RC3',
	'TemplatesXml.template.php': '1.1 RC3',
	'Templatesindex.template.php': '1.1 RC3'
};

window.smfLanguageVersions = {
	'Admin': '1.1 RC3',
	'Errors': '1.1 RC3',
	'Help': '1.1 RC3',
	'index': '1.1 RC3',
	'Install': '1.1 RC3',
	'Login': '1.1 RC3',
	'ManageBoards': '1.1 RC3',
	'ManageCalendar': '1.1 RC3',
	'ManageMembers': '1.1 RC3',
	'ManagePermissions': '1.1 RC3',
	'ManageSmileys': '1.1 RC3',
	'Manual': '1.1 RC3',
	'ModSettings': '1.1 RC3',
	'Modifications': '1.1 RC3',
	'Packages': '1.1 RC3',
	'PersonalMessage': '1.1 RC3',
	'Post': '1.1 RC3',
	'Profile': '1.1 RC3',
	'Reports': '1.1 RC3',
	'Search': '1.1 RC3',
	'Settings': '1.1 RC3',
	'Stats': '1.1 RC3',
	'Themes': '1.1 RC3',
	'Who': '1.1 RC3',
	'Wireless': '1.1 RC3'
};
<?php
}
// Normal user?
else
{
?>
window.smfVersions = {
	'SMF': 'SMF 1.0.8',
	'SourcesAdmin.php': '1.0.4',
	'SourcesBoardIndex.php': '1.0',
	'SourcesCalendar.php': '1.0.3',
	'SourcesDisplay.php': '1.0.1',
	'SourcesDumpDatabase.php': '1.0',
	'SourcesErrors.php': '1.0.2',
	'SourcesHelp.php': '1.0',
	'SourcesInstantMessage.php': '1.0.2',
	'SourcesKarma.php': '1.0',
	'SourcesLoad.php': '1.0.2',
	'SourcesLockTopic.php': '1.0.6',
	'SourcesLogInOut.php': '1.0.2',
	'SourcesManageAttachments.php': '1.0.1',
	'SourcesManageBoards.php': '1.0.1',
	'SourcesManageMembers.php': '1.0.6',
	'SourcesManagePermissions.php': '1.0',
	'SourcesManageSmileys.php': '1.0.2',
	'SourcesMemberlist.php': '1.0.6',
	'SourcesMessageIndex.php': '1.0',
	'SourcesModSettings.php': '1.0.1',
	'SourcesModlog.php': '1.0',
	'SourcesMoveTopic.php': '1.0.1',
	'SourcesNews.php': '1.0.3',
	'SourcesNotify.php': '1.0',
	'SourcesPackageGet.php': '1.0.1',
	'SourcesPackages.php': '1.0.1',
	'SourcesPoll.php': '1.0.7',
	'SourcesPost.php': '1.0.8',
	'SourcesPrintpage.php': '1.0',
	'SourcesProfile.php': '1.0.8',
	'SourcesQueryString.php': '1.0.8',
	'SourcesRecent.php': '1.0.2',
	'SourcesRegister.php': '1.0.3',
	'SourcesReminder.php': '1.0',
	'SourcesRemoveTopic.php': '1.0.1',
	'SourcesRepairBoards.php': '1.0',
	'SourcesSSI.php': '1.0.6',
	'SourcesSearch.php': '1.0.7',
	'SourcesSecurity.php': '1.0.2',
	'SourcesSendTopic.php': '1.0',
	'SourcesSplitTopics.php': '1.0',
	'SourcesStats.php': '1.0',
	'SourcesSubs.php': '1.0.6',
	'SourcesSubs-Auth.php': '1.0.3',
	'SourcesSubs-Boards.php': '1.0.5',
	'SourcesSubs-Graphics.php': '1.0',
	'SourcesSubs-Package.php': '1.0.3',
	'SourcesSubs-Post.php': '1.0.3',
	'SourcesThemes.php': '1.0.2',
	'SourcesViewQuery.php': '1.0',
	'SourcesWho.php': '1.0',
	'DefaultAdmin.template.php': '1.0.4',
	'DefaultBoardIndex.template.php': '1.0.1',
	'DefaultCalendar.template.php': '1.0',
	'DefaultDisplay.template.php': '1.0.3',
	'DefaultErrors.template.php': '1.0',
	'DefaultHelp.template.php': '1.0',
	'DefaultInstantMessage.template.php': '1.0',
	'DefaultLogin.template.php': '1.0',
	'DefaultManageAttachments.template.php': '1.0',
	'DefaultManageBoards.template.php': '1.0',
	'DefaultManageMembers.template.php': '1.0',
	'DefaultManagePermissions.template.php': '1.0',
	'DefaultManageSmileys.template.php': '1.0',
	'DefaultMemberlist.template.php': '1.0',
	'DefaultMessageIndex.template.php': '1.0',
	'DefaultModlog.template.php': '1.0',
	'DefaultMoveTopic.template.php': '1.0',
	'DefaultNotify.template.php': '1.0',
	'DefaultPackages.template.php': '1.0.1',
	'DefaultPoll.template.php': '1.0.3',
	'DefaultPost.template.php': '1.0',
	'DefaultPrintpage.template.php': '1.0',
	'DefaultProfile.template.php': '1.0.4',
	'DefaultRecent.template.php': '1.0.1',
	'DefaultRegister.template.php': '1.0',
	'DefaultReminder.template.php': '1.0',
	'DefaultSearch.template.php': '1.0',
	'DefaultSendTopic.template.php': '1.0',
	'DefaultSettings.template.php': '1.0',
	'DefaultSplitTopics.template.php': '1.0',
	'DefaultStats.template.php': '1.0',
	'DefaultThemes.template.php': '1.0',
	'DefaultWho.template.php': '1.0',
	'DefaultWireless.template.php': '1.0.1',
	'Defaultindex.template.php': '1.0',
	'TemplatesAdmin.template.php': '1.0.4',
	'TemplatesErrors.template.php': '1.0',
	'TemplatesBoardIndex.template.php': '1.0.1',
	'TemplatesCalendar.template.php': '1.0',
	'TemplatesDisplay.template.php': '1.0.3',
	'TemplatesErrors.template.php': '1.0',
	'TemplatesHelp.template.php': '1.0',
	'TemplatesInstantMessage.template.php': '1.0',
	'TemplatesLogin.template.php': '1.0',
	'TemplatesManageAttachments.template.php': '1.0',
	'TemplatesManageBoards.template.php': '1.0',
	'TemplatesManageMembers.template.php': '1.0',
	'TemplatesManagePermissions.template.php': '1.0',
	'TemplatesManageSmileys.template.php': '1.0',
	'TemplatesMemberlist.template.php': '1.0',
	'TemplatesMessageIndex.template.php': '1.0',
	'TemplatesModlog.template.php': '1.0',
	'TemplatesMoveTopic.template.php': '1.0',
	'TemplatesNotify.template.php': '1.0',
	'TemplatesPackages.template.php': '1.0.1',
	'TemplatesPoll.template.php': '1.0.3',
	'TemplatesPost.template.php': '1.0',
	'TemplatesPrintpage.template.php': '1.0',
	'TemplatesProfile.template.php': '1.0.4',
	'TemplatesRecent.template.php': '1.0.1',
	'TemplatesRegister.template.php': '1.0',
	'TemplatesReminder.template.php': '1.0',
	'TemplatesSearch.template.php': '1.0',
	'TemplatesSendTopic.template.php': '1.0',
	'TemplatesSettings.template.php': '1.0',
	'TemplatesSplitTopics.template.php': '1.0',
	'TemplatesStats.template.php': '1.0',
	'TemplatesThemes.template.php': '1.0',
	'TemplatesWho.template.php': '1.0',
	'TemplatesWireless.template.php': '1.0.1',
	'Templatesindex.template.php': '1.0'
};

window.smfLanguageVersions = {
	'Admin': '1.0.4',
	'Errors': '1.0',
	'Help': '1.0',
	'index': '1.0.1',
	'Install': '1.0',
	'InstantMessage': '1.0',
	'Login': '1.0',
	'ManageBoards': '1.0',
	'ManageMembers': '1.0',
	'ManagePermissions': '1.0',
	'ManageSmileys': '1.0',
	'ModSettings': '1.0',
	'Modifications': '1.0',
	'Packages': '1.0.1',
	'Post': '1.0',
	'Profile': '1.0',
	'Settings': '1.0',
	'Stats': '1.0',
	'Themes': '1.0',
	'Who': '1.0',
	'Wireless': '1.0'
};
<?php
}
?>