name: Update Year

on:
  workflow_dispatch:

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set current year environment variable
      run: echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV

    - name: Check if version tag matches any pre-release
      id: check_version
      run: |
        str=$(grep -oP "define\('SMF_VERSION', '[^']+" SSI.php)
        echo $str;
        re='[0-9]+\.[0-9]+ [A-Za-z]+';
        if [[ $str =~ $re ]]; then
          echo "PRE_RELEASE=true" >> $GITHUB_ENV
        else
          echo "PRE_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Update year in Sources/
      if: env.PRE_RELEASE == 'true'
      run: |
        shopt -s globstar
        for file in Sources/**/*.php; do
          sed -i "s/define('SMF_SOFTWARE_YEAR', '[0-9]\{4\}');/define('SMF_SOFTWARE_YEAR', '${{ env.CURRENT_YEAR }}');/" $file
        done

    - name: Update year in PHP files
      if: env.PRE_RELEASE == 'false'
      run: |
        for file in SSI.php proxy.php cron.php index.php; do
          sed -i "s/define('SMF_SOFTWARE_YEAR', '[0-9]\{4\}');/define('SMF_SOFTWARE_YEAR', '${{ env.CURRENT_YEAR }}');/" $file
        done

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update year to ${{ env.CURRENT_YEAR }}
        branch: 2.1/update-year-${{ env.CURRENT_YEAR }}
        title: "[2.1] Update year to ${{ env.CURRENT_YEAR }}"
        body: This PR updates the year to ${{ env.CURRENT_YEAR }} in all PHP files in Sources/ if the version tag in SSI.php matches any pre-release.